name: Update Rules

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

concurrency:
  group: rules
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Install sing-box
        run: |
          VERSION="1.13.3"
          curl -L https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/sing-box-${VERSION}-linux-amd64.tar.gz -o sb.tar.gz
          tar -xzf sb.tar.gz
          sudo mv sing-box-*/sing-box /usr/local/bin/

      # ✅ main.py 在根目录，rule/output 放到 rule 文件夹
      - name: Run main.py
        run: python main.py

      - name: Commit
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add rule/*.json rule/*.srs
          git diff --staged --quiet || git commit -m "update rules"
          git push
